### ISSUE TITLE
Hey, man, it's cool. I like it very much. Thank you. Can you change the window class name of the cheating engine

### ISSUE THREAD

**Issue by YMY1666527646** [HawkeyeZAR/CheatEnginePlugins#1]

**Comment by HawkeyeZAR** [comment]
Yes, updating the Title is pretty easy and a quick fix.  I have made the changes so you will now be able to change the title for cheat engine.  

This however wont change the running process name for cheat engine, in task manager it will still show cheatengine-x86_64.exe.  If you want to change the process name as well, you can try renaming the exe file ("ce-x86_64.exe").
